version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    volumes:
      - .:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
